### PR TITLE
Update setups for webpack 2

### PR DESCRIPTION
**Pull request by colus001**
Love your template!

- Fix `resolve.root` -> `resolve.module`
- Fix `module.loaders` -> `module.rules`
- Fix `module.loaders.query` to `module.loaders.options`
- Update package.json

### CODE REVIEW

**Comment by mz026** [comment]
Thanks for the upgrading! @colus001 

I ran the code after `yarn install` and got compile error on browser side, please see the attachment.
err

Also, can you please update `yarn.lock` accordingly?

**Comment by alma-socar** [comment]
@mz026 Okay, I'll check that.

**Comment by alma-socar** [comment]
I couldn't find why this is happening. It seems front-end bundling is not working properly.

http://stackoverflow.com/questions/41844853/migrating-to-webpack-2-and-encountered-uncaught-syntaxerror-unexpected-token

I left question on stackoverflow. I'll follow up this problem.

**Comment by colus001** [comment]
@mz026 I couldn't find why this is happening. It seems front-end bundling is not working properly.

http://stackoverflow.com/questions/41844853/migrating-to-webpack-2-and-encountered-uncaught-syntaxerror-unexpected-token

I left question on stackoverflow. I'll follow up this problem.

**Comment by colus001** [comment]
I found out what the problem is.

Since [webpack 2 support for ES6 native modules](https://gist.github.com/sokra/27b24881210b56bbaff7), when you transpile, you should set `.babelrc` es2015 with `{ "modules": false }`. So it would be like below

```
{
  "presets": [
    [ "es2015", { "modules": false } ],
    "react"
  ],
}
```

And then another problem comes out. Since we have `nodemon app/server` when `yarn start`, it relies only on `babel` not with webpack.

```
    "start": "cross-env NODE_PATH=./app concurrently --kill-others \"nodemon app/server\" \"node webpack.server.js\" \"gulp css:watch\"",
```

Then with `{ modules: false }` on `.babelrc`, it shows syntax error since node has not fully supported native module import.

```
import Express from 'express';
^^^^^^
SyntaxError: Unexpected token import
```

Quick solution would be to remove `native module import` of webpack 2 if it's possible. What do you think?

**Comment by mz026** [comment]
@colus001 I might need to survey a little bit more to answer that question.. :stuck_out_tongue:

**Comment by mz026** [comment]
@colus001 I think the `modules: false` in `.babelrc` might not be the root cause. After some survey and testing, I found the `Unexpected Token .` is caused from the the fact that [`DefinePlugin` failed to inject `process.env.NODE_ENV` correctly](https://github.com/webpack/webpack/issues/868).

A quick fix is to make the content in `DefinePlugin` something like this:

```javascript
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': '"development"'
    })
```

but [using EnvironmentPlugin](https://github.com/mz026/universal-redux-template/commit/214fe5a) is a better solution in my opinion. I just upgraded the master branch and did some tweaks.

As for the question

> Quick solution would be to remove native module import of webpack 2 if it's possible. What do you think?

I think to branch the behavior of Babel between webpack and node on server side, [passing options when `register`-ing](https://babeljs.io/docs/usage/babel-register/#specifying-options) is more elegant to me. But this is not directly related to the webpack2 upgrading issue.

**Comment by mz026** [comment]
Just noticed I mis-pasted the issue, [this one](https://github.com/webpack/webpack/issues/4000) is the correct version. (sorry about that :stuck_out_tongue: )

For the upgrading case, the thing is that `DefinePlugin`'s behavior changes between webpack 1 and 2:

In webpack2, the compiled line caused the syntax error was:

```
if ({}.NODE_ENV !== 'production')
```

while in webpack1, the compiled line was:

```
if (({}).NODE_ENV !== 'production')
```

`DefinePlugin` in Webpack2 didn't wrap the injected var with `()`, which caused the syntax error.

**Comment by colus001** [comment]
I'll update PR today. :D

**Comment by colus001** [comment]
Oh you did update. Thanks. :D

**Pull request closed without merging**
