### PR TITLE
Fixed wrong production assets path

### PR DESCRIPTION
**Pull request by TylorShin**

### CODE REVIEW

**Comment by mz026** [comment]
@TylorShin thanks!

**Comment by TylorShin** [comment]
I think that this package is very easy and simple to use. so I loved it, but I think it need some fixing stuff too :+1: 

but I wonder that SSR working nicely at production mode?

**Comment by mz026** [comment]
@TylorShin  The mechanisms of SSR are the same in both development and production mode, so it should behave the same in both modes. My team host a [couple](https://www.refactor.io/) [projects](http://bestprogramminglanguagefor.me/) based on this template, so I think it has been tested on production environments.

However, the current bode base didn't handle the configuration stuff (mainly the API base URL part) so there might be some issues when deploying it directly out of local machine without any additional configurations. I've left it in the TODO part for a while as I think the configuration ways might vary with each project and team, but I think I can add the the way of my team into the repo. 

I created an issue for this to track it: https://github.com/mz026/universal-redux-template/issues/6

Thanks for raising it up!

**Comment by TylorShin** [comment]
I'll look forward it too :+1:

**Comment by mz026** [comment]
@TylorShin actually it's done :smile: , please see the following comparison: https://github.com/mz026/universal-redux-template/compare/d9b9e7a...7033ba4

**Pull request merged**
